spring:
    application:
        name: libraryapi
    profiles:
        active: ${SPRING_PROFILES_ACTIVE}

    datasource:
        url: ${DATASOURCE_URL}
        username: ${USERNAME}
        password: ${PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            # ddl-auto: update
            ddl-auto: none
        # properties:
        #     'hibernate.format_sql': true
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
logging:
    file:
        name: app.log
    level:
        root: warn
        io:
            github:
                sergiohscl: trace
        org:
            springframework:
                web: debug
                security: trace
springdoc:
    override-with-generic-response: false

# production
---
spring:
    config:
        activate:
            on-profile: production
    jpa:
        show-sql: false


# homologacao
---
spring:
    config:
        activate:
            on-profile: homologacao
    jpa:
        show-sql: false
    datasource:
        url: jdbc:postgresql://localhost:5432/library